stages:
  - build
  - where-am-i

job_build:
  stage: build
  script:
    - echo "Building the project"
    - date | tee -a /tmp/gitlab-build
    - hostname | tee -a /tmp/gitlab-build
    - cat /etc/os-release
    - ps -ef
    - curl -s ipinfo.io
    - cat /proc/1/cmdline
    - cat /tmp/gitlab-build

where-am-i:
  tags:
    - local                    # must match a tag on your runner
  script:
    - echo "Runner ID:    $CI_RUNNER_ID"
    - echo "Description:  $CI_RUNNER_DESCRIPTION"
    - echo "Tags:         $CI_RUNNER_TAGS"
    - echo "Version:      $CI_RUNNER_VERSION"
    - echo "Hostname:     $(hostname)"
    - echo "User:         $(whoami)"
    - echo "my-laptop-$(date +%s) | $CI_RUNNER_ID " >> ~/runner-proof.txt
    - uname -a