# default:
#   tags:
#     - linux-arm64

stages:
  - build
  - where-am-i
  - test1
  - test2 

job_build:
  stage: build
  tags:
    - linux-arm64  
  script:
    - |
      echo "Building the project on $CI_RUNNER_ID ($CI_RUNNER_TAGS)"
      date | tee -a /tmp/gitlab-build
      hostname | tee -a /tmp/gitlab-build
      cat /etc/os-release
      cat /proc/1/cmdline; echo
      echo "Runner ID:    $CI_RUNNER_ID"
      echo "Description:  $CI_RUNNER_DESCRIPTION"
      echo "Tags:         $CI_RUNNER_TAGS"

where-am-i:
  stage: where-am-i
  tags:
    - linux-arm64
  script:
    - |
      echo "Runner ID:    $CI_RUNNER_ID"
      echo "Description:  $CI_RUNNER_DESCRIPTION"
      echo "Tags:         $CI_RUNNER_TAGS"
      echo "Hostname:     $(hostname)"
      echo "User:         $(whoami)"
      uname -a
      echo "marker: my-laptop-$(date +%s)-$CI_RUNNER_ID" >> ~/gitlab-run
      ls -l ~/gitlab-run && pwd

test1:
  stage: test1
  tags:
    - docker-arm64
  script:
    - sleep 5
    - |
      echo "Building the project on $CI_RUNNER_ID ($CI_RUNNER_TAGS)"
      echo "Runner ID:    $CI_RUNNER_ID"
      echo "Description:  $CI_RUNNER_DESCRIPTION"
      echo "Tags:         $CI_RUNNER_TAGS"
      cat /proc/1/cmdline; echo

test2:
  stage: test2
  script:
    - sleep 1
    - echo "Building the project on $CI_RUNNER_ID ($CI_RUNNER_TAGS)"
    - |
      echo "Runner ID:    $CI_RUNNER_ID"
      echo "Description:  $CI_RUNNER_DESCRIPTION"
      echo "Tags:         $CI_RUNNER_TAGS"
      cat /proc/1/cmdline; echo
      wget ipinfo.io && cat index.html; echo       
