version: 2.1

description: "This uses Trufflehog to search pull requests for secrets."

orbs:
  scanner: atul/secrets-scanner-orb@dev:alpha

workflows:
  base-workflow:
    jobs:
      - scan-with-git-secrets
      - scan-with-trufflehog
      - scanner/scan-git-secrets
      - scanner/scan-trufflehog

jobs:
  scan-with-git-secrets:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - scanner/git-secrets-scan

  scan-with-trufflehog:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - scanner/trufflehog-scan